NNPTP20-1 Refactoring-Develop-st64297
rodi0878/NNPTP20-1 pull request #11
Opened 2020-11-10 20:53 UTC by George222cz

Dobrý den,
prosím o kontrolu mého refactoringu projektu NNPTP20-1.
Jiří Dřímal

2020-11-12 12:15 UTC, rodi0878 requested changes
Podívejte se na zmíněné problémy, je to potřeba ještě trochu vylepšit

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +            public float Imaginary { get; set; }
proč je jeden člen double a druhý float?

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +            public ComplexNumber Initialize(double xmin, double ymin, double xstep, double ystep, int x, int y)
tato metoda nijak nesouvisí s obecným konceptem kompexního čísla a nemá tu co dělat

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +            public double GetAbS()
Ab**S** ?

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +            public double GetAngleInDegrees()
MAGIE ! Math.Atan - "An angle, θ, measured in **radians**, such that -π/2 ≤ θ ≤ π/2."

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +                    return inputComplexNumber.Real == Real && inputComplexNumber.Imaginary == Imaginary;
== není vhodný způsob pro porovnávání double a float hodnot

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/INPTPZ1.csproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
.user soubor je uživatelská konfigurace IDE a nemělo by to být v repozitáři

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/Poly.cs
> +        public class Poly
nevhodný název souboru a třídy

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/Program.cs
>          static void Main(string[] args)
příliš dlouhá a komplexní metoda

2020-11-12 12:15 UTC, rodi0878 commented on INPTPZ1/Program.cs
> +        private static void ColorizePixel(Bitmap bitmap, Color[] colors, int x, int y, int iteration, int rootIndex)
příliš mnoho vstupních parametrů

2020-11-20 18:35 UTC, George222cz commented
Dobrý den,
připomínky jsem snad opravil - prosím o kontrolu.
Předem děkuji
Jiří Dřímal

2020-12-08 14:09 UTC, rodi0878 requested changes
Jedna z připomínek nebyla nijak reflektována, prosím o komentář nebo úpravu.

2020-12-08 14:09 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +                    return inputComplexNumber.Real == Real && inputComplexNumber.Imaginary == Imaginary;
stále nevyřešeno

2020-12-08 15:11 UTC, George222cz commented
Pardon, špatně jsem pochopil vaši připomínku.
Ten řádek by měl správně vypadat asi takto:
return inputComplexNumber.Real.Equals(Real) && inputComplexNumber.Imaginary.Equals(Imaginary);
Popřípadě jsem ještě našel (https://stackoverflow.com/a/40653822) toto řešení:
return Math.Abs(inputComplexNumber.Real - Real) < 0.0000001 && Math.Abs(inputComplexNumber.Imaginary - Imaginary) < 0.0000001;

2020-12-15 08:52 UTC, rodi0878 commented
Akceptováno

2020-12-15 08:52 UTC, closed without merging