Final refactoring by st52165
rodi0878/NNPTP20-1 pull request #12
Opened 2020-11-14 21:43 UTC by st52165

Dobrý večer, 
posílám Vám finální verzi čištění kódu u projektu NNPTP20-1.

2020-12-08 14:15 UTC, rodi0878 requested changes
Celkově je to velmi dobré, ale našel jsem pár drobností, které by stály ještě k zamyšlení.

2020-12-08 14:15 UTC, rodi0878 commented on INPTPZ1/INPTPZ1.csproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
.user soubor obsahuje uživatelskou konfiguraci a nemá co dělat v repozitáři

2020-12-08 14:15 UTC, rodi0878 commented on Mathematics/NewtonFractal.cs
> +        private static Color MultiplyColor(Color basic, int coefficient)
název nevyjadřuje smysl metody

2020-12-08 14:15 UTC, rodi0878 commented on INPTPZ1Tests/CplxTests.cs
> -﻿using Microsoft.VisualStudio.TestTools.UnitTesting;
není žádoucí odstraňovat korektní testy

2020-12-08 18:40 UTC, st52165 commented
Dobrý večer,
děkuji za Vaše připomínky. Zmíněné nedostatky jsem opravil. Nyní již snad bude vše v pořádku.

2020-12-15 08:53 UTC, rodi0878 commented
Akceptováno

2020-12-15 08:53 UTC, closed without merging