Cleaning the code
rodi0878/NNPTP20-1 pull request #17
Opened 2020-12-16 01:10 UTC by Domel303

Cleaning the code. Creating new classes and methods instead of having all logic in one class. Refactoring names of variables and methods.

2020-12-20 12:23 UTC, rodi0878 requested changes
Code contains naming errors please fix them before merge.

2020-12-20 12:23 UTC, rodi0878 commented on INPTPZ1/Fractals/NewtonFractals.cs
> +        private int findRoot(List<Complex> roots, Complex coordinates)
method naming convention is not respected

2020-12-20 12:23 UTC, rodi0878 commented on INPTPZ1/Fractals/NewtonFractals.cs
> +        private static Polynomial StartFunction()
methods should have a verb in their name - also repeats for many other methods below this

2020-12-20 12:23 UTC, rodi0878 commented on INPTPZ1/Fractals/NewtonFractals.cs
> +        private static readonly Color[] colors =
why "colors" when you have "IterationLimit" and others...

2020-12-20 12:23 UTC, rodi0878 commented on INPTPZ1/INPTPZ1.csproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
user configuration files must not be added to repository

2020-12-20 19:18 UTC, Domel303 commented
@rodi0878 Errors were fixed.

2020-12-24 09:11 UTC, rodi0878 commented
Accepted

2020-12-24 09:11 UTC, closed without merging