NNPTP20-1 refactor by st55425
rodi0878/NNPTP20-1 pull request #5
Opened 2020-10-19 20:32 UTC by st55425

Dobrý den, zde je má verze čistého kódu projektu NNPTP20-1

2020-10-29 10:39 UTC, rodi0878 requested changes
Několik drobností je třeba ještě vyřešit. Fatální chybou je rovněž commitnutí "out.png".

2020-10-29 10:39 UTC, rodi0878 commented on INPTPZ1/ArgumentManager.cs
> +            int pathIndex = 6;
Nevhodné umístění a formát (obyčejná proměnná) pro konstantní indexy, týká se i následujících obdobných výskytů.

2020-10-29 10:39 UTC, rodi0878 commented on INPTPZ1/FractalManager.cs
> +            for (int i = 0; i < ExaminedFunction.FindedRoots.Count; i++)
"Found"

2020-10-29 10:39 UTC, rodi0878 commented on INPTPZ1/ImageManager.cs
> +        private FractalManager fractalManager;
Nejednotný styl - někde začínáte malým písmenem, někde velkým.

2020-10-29 11:53 UTC, st55425 commented on INPTPZ1/ArgumentManager.cs
> +            int pathIndex = 6;
out.png odstraněn, indexy předělány

2020-10-29 11:53 UTC, st55425 commented on INPTPZ1/FractalManager.cs
> +            for (int i = 0; i < ExaminedFunction.FindedRoots.Count; i++)
Opraveno

2020-10-29 11:53 UTC, st55425 commented on INPTPZ1/ImageManager.cs
> +        private FractalManager fractalManager;
Sjednoceno

2020-11-01 15:08 UTC, rodi0878 commented
Akceptováno

2020-11-01 15:08 UTC, closed without merging