Develop st52542
rodi0878/NNPTP20-1 pull request #6
Opened 2020-10-20 23:36 UTC by st52542

Dobrý den, zde je moje verze čistého kódu pro projekt NNPTP20-1.

2020-10-29 10:43 UTC, rodi0878 requested changes
Několik drobností je třeba ještě vyřešit...

2020-10-29 10:43 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +                    return compareWithPartsOfComplexNumber.RealPartOfNumber == RealPartOfNumber && compareWithPartsOfComplexNumber.ImaginarPartOfNumber == ImaginarPartOfNumber;
https://docs.microsoft.com/cs-cz/dotnet/api/system.double.equals?view=netcore-3.1

2020-10-29 10:43 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +        private static int bitmapWidht, bitmapHeight;
typo

2020-10-29 10:43 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +        private static string output;
output?

2020-10-29 10:43 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +        private static void Variables(string[] args)
Proměnné? Co? Chybí sloveso, nedává smysl.

2020-10-29 10:43 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +        static void Main(string[] args)
Příliš dlouhé a příliš komplexní main

2020-10-29 13:22 UTC, st52542 commented on INPTPZ1/NewtonFractal.cs
> +        static void Main(string[] args)
Opraveno

2020-10-29 13:22 UTC, st52542 commented on INPTPZ1/NewtonFractal.cs
> +        private static void Variables(string[] args)
Opraveno

2020-10-29 13:22 UTC, st52542 commented on INPTPZ1/NewtonFractal.cs
> +        private static string output;
Opraveno

2020-10-29 13:22 UTC, st52542 commented on INPTPZ1/NewtonFractal.cs
> +        private static int bitmapWidht, bitmapHeight;
Opraveno

2020-10-29 13:23 UTC, st52542 commented on INPTPZ1/ComplexNumber.cs
> +                    return compareWithPartsOfComplexNumber.RealPartOfNumber == RealPartOfNumber && compareWithPartsOfComplexNumber.ImaginarPartOfNumber == ImaginarPartOfNumber;
Opraveno

2020-10-29 13:30 UTC, st52542 commented
Drobnosti jsem opravil.

2020-11-01 15:10 UTC, rodi0878 commented
Akceptováno

2020-11-01 15:10 UTC, closed without merging