Clean code and refactoring
rodi0878/NNPTP20-1 pull request #7
Opened 2020-10-21 09:32 UTC by st55774

Prosím o kontrolu čistění kódu a případné připomínky.
Děkuji

2020-10-29 10:50 UTC, rodi0878 requested changes
Několik drobností by tu bylo ještě k zamyslění a úpravě... Mrkněte se na to

2020-10-29 10:50 UTC, rodi0878 commented on INPTPZ1/Mathematics/Complex.cs
> +        public bool IsRoot(Complex root)
Nevhodné řešení - k tomuto slouží equals. IsRoot nemá z pohledu komplexního čísla smysl

2020-10-29 10:50 UTC, rodi0878 commented on INPTPZ1/NewtonFractals/NewtonFractalsManager.cs
> +        private static List<Complex> Initial()
Initial co?

2020-10-29 10:50 UTC, rodi0878 commented on INPTPZ1/Mathematics/Polynomial.cs
> +            Complex evaluationIndex = evaluation;
Nevhodné pojmenování

2020-10-29 11:45 UTC, st55774 commented on INPTPZ1/Mathematics/Complex.cs
> +        public bool IsRoot(Complex root)
Děkuji za připomínku. Po opětovném nahlédnutí do kódu jsem zjistil, že původní metoda Equals se nikde nevyužvá. Nahradil jsem tedy její tělo metodou IsRoot.

2020-10-29 11:46 UTC, st55774 commented on INPTPZ1/NewtonFractals/NewtonFractalsManager.cs
> +        private static List<Complex> Initial()
Nahradil jsem názvem "Examined". Snad bude výstižnější.

2020-10-29 11:46 UTC, st55774 commented on INPTPZ1/Mathematics/Polynomial.cs
> +            Complex evaluationIndex = evaluation;
Nahradil jsem názvem "CoefficientMultiplication". Snad bude více odpovídat významu metody.

2020-10-29 11:47 UTC, st55774 commented
@rodi0878 
Děkuji za feedback. Připomínky jsem snad správně opravil. Prosím Vás o opětovnou kontrolu.

2020-11-01 15:12 UTC, rodi0878 commented
Akceptováno

2020-11-01 15:12 UTC, closed without merging